import Head from 'next/head'
import Router, { useRouter } from 'next/router'
import { useState } from 'react'
import { API } from './api/API'
import { Container, Game, PlayersBigBox, Versus , Player,PlayerBox , Score } from './styles/GamePageStyles.js'

export default function GamePage(){

  const router = useRouter()

  //const [Index, SetIndex] = useState(0 || "")
  let Index = 0;
  //const [ScoreNumber, SetScoreNumber] = useState(0 || "")
  let ScoreNumber = 0;
  const [Did, SetDid] = useState(true)

  function Higher (){
    if (Did) {
      SetDid(false)
      Index = 1;
    } 
    if (API[router.query.array[Index + 1]].salary >= API[router.query.array[Index]].salary){
      Index++;
      ScoreNumber++;

      if ((Index + 1) === 18){
        Router.push({
          pathname: '/FinalPage',
          query: { 
            result: ScoreNumber,
            state: 'winner'
          }
        })
      }
    } else {
      Router.push({
        pathname: '/FinalPage',
        query: { 
          result: ScoreNumber,
          state: 'loser'
        }
      })
    }
  }

  function Lower (){
    if (Did) {
      SetDid(false)
    } 
      
    if (API[router.query.array[Index + 1]].salary < API[router.query.array[Index]].salary){
      Index++;
      ScoreNumber++;

      if ((Index + 1) === 18){
        Router.push({
          pathname: '/FinalPage',
          query: { 
            result: ScoreNumber,
            state: 'winner'
          }
        })
      }
    } else {
      Router.push({
        pathname: '/FinalPage',
        query: { 
          result: ScoreNumber,
          state: 'loser'
        }
      })
    }
  }

  return (
    
      <Container>
        <Head>
          <title>NBA Higher or Lower</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Game>
          <PlayersBigBox>
            <Versus>VS</Versus>
            <Score>Score: {ScoreNumber}</Score>
            <PlayerBox>
              <Player img={API[router.query.array[Index]].image}/>
                <h1 className='First'>
                  {API[router.query.array[Index]].name + " " + API[router.query.array[Index]].lastname}
                </h1>
                <h2 className='Number'>
                  {Intl.NumberFormat('en-EU', {style: 'currency',currency: 'USD', minimumFractionDigits: 0}).format(API[ArrayNumbers[Index]].salary)}
                </h2>
            </PlayerBox>
            <PlayerBox>
              <Player img={API[router.query.array[Index + 1]].image}/>
                <h1 className='Second'>
                  {API[router.query.array[Index + 1]].name + " " + API[router.query.array[Index + 1]].lastname}
                </h1>
                <h3 className='Cobra'>
                  Cobra...
                </h3>
                <section className='Buttons'>
                  <button onClick={() => { Higher() } }>Más</button>
                  <button onClick={() => { Lower() } }>Menos</button>
                </section>
            </PlayerBox>
          </PlayersBigBox>
        </Game>
      </Container>
  )

  
}
